#include <jni.h>
#include "integration_CalculatorBridge.h"   // generated by javac -h
#include "calc_engine.h"                    // M2’s header

JNIEXPORT jstring JNICALL Java_integration_CalculatorBridge_calculateRPN
  (JNIEnv *env, jobject obj, jdouble num1, jdouble num2, jchar operator) {
    
    // Call M2’s native function
    char* result = calculate_rpn(num1, num2, operator);

    // Convert C string (char*) to Java String
    return (*env)->NewStringUTF(env, result);
}
