/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class integration_CalculatorBridge */

#ifndef _Included_integration_CalculatorBridge
#define _Included_integration_CalculatorBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     integration_CalculatorBridge
 * Method:    calculateRPN
 * Signature: (DDC)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_integration_CalculatorBridge_calculateRPN
  (JNIEnv *, jobject, jdouble, jdouble, jchar);

#ifdef __cplusplus
}
#endif
#endif
